name: My First Workflow (Not really)
on:
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    name: My First Job!
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}"
          echo "Current branch is '${{ github.ref }}"
          echo "My secret is ${{ secrets.MY_SECRET }}"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is  '$sec'."
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is  '$sec'."
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://katcodes.dev
    needs: [Test, Load-Test]
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is  '$sec'."
